### ISSUE TITLE
Dead Youtube link (ROS Exam preparation)

### ISSUE THREAD

**Issue by spectaA** [norlab-ulaval/percep3d_students#3]
Attack of the Killer Tomatoes in SPACE video is no longer available : [Link](https://www.youtube.com/watch?v=clqDkCJs19s&t=5s)
File : percep3d_students/lessons/ros/6-exam_ros.ipynb

**Comment by pomerlef** [comment]
Nooooo, one of the best part. Here is a new link: https://youtu.be/txfdGlxEsG8

**Comment by WilliamDubois** [comment]
Fixed
